### ISSUE TITLE
Premier Lancement de l'application

### ISSUE THREAD

**Issue by therealcorwin** [therealcorwin/MAGECO#20]
Lors du premier lancement de l'application, il sera nécessaire d’effectuer plusieurs taches :

- [ ] Déterminer si c'est le premier lancement de l'application ou non

- [ ] Vérification de la présence des fichiers de conf

- [ ] Création des fichiers de conf le cas échéant 

- [ ] mise en place de log pour suivre la vie de l'app et les actions de l'utilisateur

- [ ] Paramétrage de l'app (utilisation bdd locale/distante)

- [ ] Création de la BDD
